### ISSUE TITLE
Making sure it doesn't connect to pods from different deployments

### ISSUE THREAD

**Issue by jeroenvisser101** [edevil/elixir_kubernetes_cluster#1]
Currently, I believe that during a deploy, it's possible that nodes from different versions could connect with eachother (the deployment id is matched but not used [here](https://github.com/edevil/elixir_kubernetes_cluster/blob/master/lib/elixir_kubernetes_cluster/elixir_kubernetes_cluster_worker.ex#L13-L14)).

Did you encounter any issues with this, or is this maybe handled somewhere else?

**Comment by edevil** [comment]
This is not handled somewhere else. As you said, the deployment id is available, but I haven't encountered problems of different versions connecting to one another. At least not yet.

So for now I think its better to be able to connect to every node while the rolling update is taking place.

**Comment by jeroenvisser101** [comment]
Right. I'm not sure what could happen if old nodes connect to the new ones.

**Comment by jeroenvisser101** [comment]
@edevil I'll close this, and if I ever encounter something related to this, I'll let you know. Thanks so much for releasing this! You rock! 👍

**Comment by edevil** [comment]
:) Thank you.
